name: check runner

on:
  workflow_dispatch: {}

jobs:
  check-runner:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:
      - name: Build-and-push-image
        id: build-and-push-image
        run: |
          docker build . -t test_tag -f ./new.Dockerfile
