name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  docker-build:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: false
          load: true
          tags: crozzy/great-app:${{ github.sha }}

      - name: Save image
        run: |
          docker save -o /tmp/${{ github.sha }} crozzy/great-app:${{ github.sha }}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: built-image
          path: /tmp/${{ github.sha }}

  scan-container:
    name: "Scan Container"
    needs: ['docker-build']
    runs-on: ubuntu-latest
    container: quay.io/crozzy/local-clair:latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: built-image
          path: /tmp
      - name: Scan Image
        run: |
          DB_PATH=/matcher IMAGE_PATH=/tmp/${{ github.sha }} /bin/local-clair report > /tmp/${{ github.sha }}_vulnerability_report.json
      - name: Upload vulnerability report
        uses: actions/upload-artifact@master
        with:
          name: vulnerability-report
          path: /tmp/${{ github.sha }}_vulnerability_report.json
      - name: Scan results
        run: |
          microdnf install jq
          cat /tmp/${{ github.sha }}_vulnerability_report.json | jq -e ".vulnerabilities | length == 0"

