name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  docker-build:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build an image from Dockerfile
        run: |
          docker build -t crozzy/great-app:${{ github.sha }} .
      - name: Save Docker image
        run: |
          docker save -o ${{ github.sha }} crozzy/great-app:${{ github.sha }}
      - name: Run Clair V4
        uses: crozzy/local-clair@main
        with:
          image-path: ${{ github.sha }}
          format: sarif
          output: clair_results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: clair_results.sarif
