name: wipe alerts

on:
  workflow_dispatch: {}

jobs:
  clean-up:
    name: "Docker Build"
    runs-on: ubuntu-latest
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: no_vulns.sarif
